source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CocoaDemo_Example', :exclusive => true do
  pod "CocoaDemo", :path => "../"
end

target 'CocoaDemo_Tests', :exclusive => true do
  pod "CocoaDemo", :path => "../"

  
end
